### PR TITLE
(fix) Settings Page: hidden save button

### PR DESCRIPTION
**Pull request by JasonMHasperhoven**
Fixes this:
image

### CODE REVIEW

**Review by alexstotsky — APPROVED** [review]

**Review by Blaumaus — COMMENTED** [review]
Does not work for me.
Screenshot from 2021-04-07 13-48-06


But the fix below works well:
```
.hfui-settings__options {
      margin-bottom: 50px;
}
```

**Review by bhoomij — APPROVED** [review]

**Comment by JasonMHasperhoven** [comment]
Seems to work @Blaumaus :

image

**Comment by JasonMHasperhoven** [comment]
> Does not work for me.
> Screenshot from 2021-04-07 13-48-06
> 
> But the fix below works well:
> 
> ```
> .hfui-settings__options {
>       margin-bottom: 50px;
> }
> ```

Is this firefox?

**Comment by Blaumaus** [comment]
> > Does not work for me.
> > Screenshot from 2021-04-07 13-48-06
> > But the fix below works well:
> > ```
> > .hfui-settings__options {
> >       margin-bottom: 50px;
> > }
> > ```
> 
> Is this firefox?

Yes

**Pull request merged**
