### PR TITLE
(fix) orderform: show base and quote currency

### PR DESCRIPTION
**Pull request by bhoomij**
Task: [Trading Terminal: show base and quote currency in the order form]
(https://app.asana.com/0/1125859137800433/1199637468764447/f)
Sub-task: [Show base, quote currency for Price, Amount labels](https://app.asana.com/0/0/1200044397612902/f)

Before:
Screenshot 2021-03-11 at 1 10 06 PM

After:
Screenshot 2021-03-11 at 1 09 10 PM 1

### CODE REVIEW

**Review by avsek477 — APPROVED** [review]
lgtm :+1:

**Comment by alexstotsky** [comment]
Good job! 
But also highest bid/lowest ask should be added as Peter asked in this task
image

**Comment by bhoomij** [comment]
> Good job!
> But also highest bid/lowest ask should be added as Peter asked in this task
> 
> image

Right. would be good if we do highest bid/lowest ask implementation in separate task, added [subtask](https://app.asana.com/0/0/1200044397612903/f)

**Review by alexstotsky — APPROVED** [review]
lgtm

**Pull request merged**
