### PR TITLE
Fix negative amounts in the order book

### PR DESCRIPTION
**Pull request by alexstotsky**
### PR description
- Fixed order book negative amounts in `Stacked View` mode and when `Sum Amounts` disabled
- Full description https://app.asana.com/0/1125859137800433/1199667429846914

### CODE REVIEW

**Comment by AntonNazarenko** [comment]
lgtm

**Comment by robertkowalski** [comment]
what about total amount when you deselect "sum"?

Screenshot 2021-02-08 at 14 28 25

**Comment by robertkowalski** [comment]
with "sum amounts" and "stacked view":

Screenshot 2021-02-08 at 14 30 23

**Comment by alexstotsky** [comment]
no need to fix `Total` cause this column will be removed during this task
https://app.asana.com/0/1125859137800433/1199640043344214

**Comment by robertkowalski** [comment]
issue with 0 messages for "sum amounts" and "stacked view" not related to the PR, will be tackled in another PR

**Pull request merged**
