### PR TITLE
fix select scroll ( market )

### PR DESCRIPTION
**Pull request by AntonNazarenko**

### CODE REVIEW

**Comment by robertkowalski** [comment]
in the electron app, when i open it for the first time, scrolling works. then i close it, without any selection and reopen it, then i can't scroll any more

**Review by robertkowalski — CHANGES_REQUESTED** [review]
found a small issue...

**Comment by AntonNazarenko** [comment]
> in the electron app, when i open it for the first time, scrolling works. then i close it, without any selection and reopen it, then i can't scroll any more

strange... on which OS you are running? You are opening the packed app or just with npm run electron?

**Comment by robertkowalski** [comment]
i run `electron .`

**Review by robertkowalski — APPROVED** [review]
lgtm

**Pull request merged**
